### ISSUE TITLE
Not working in Sketch 49

### ISSUE THREAD

**Issue by ozgurgunes** [FrancisVega/Sketch-Smart-Style-Switcher#1]
TypeError: null is not an object (evaluating 'attrs.MSAttributedStringColorAttribute.value')

**Comment by FrancisVega** [comment]
Could you give more information? :)

**Comment by ozgurgunes** [comment]
Hi, I just pasted console log. I’ve no more information. I found your plugin which i need for a complex document and it is not working for me :/

**Comment by FrancisVega** [comment]
Could you send me a .sketch file? (with no layers, just the text styles...)

**Comment by ozgurgunes** [comment]
Here it is.

**Comment by ozgurgunes** [comment]
Link is here: https://www.dropbox.com/s/ogfi20bm1a6nmrh/Text%20Styles.sketch?dl=1

**Comment by FrancisVega** [comment]
I uploaded a new version. Could you test it ?
The problem was a text style with no color information.

**Comment by ozgurgunes** [comment]
I think its working now. Thanks for the fix. But I discovered that I've another problem. Many of my text elements have no style applied. I want to apply closest style via your plugin. Seems it doesn't work like that. Texts must have applied a style before. Could you do anything for this?

**Comment by FrancisVega** [comment]
I'm working in it, but the style attributes must match (not closest) the target text style.
Thanks!

**Comment by ozgurgunes** [comment]
Yep, they match, my mistell, sorry.

**Comment by FrancisVega** [comment]
Ok, I updated plugin with that "feature" :D

**Comment by ozgurgunes** [comment]
You're great. I can test it some couple hours later. I come here again if I find any problem. Thanks a lot mate.
